In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data = pd.read_csv('flight_wifi_data.csv')

In [ ]:
data

In [5]:
data.head()

,id,flight_number,origin,destination,departure_date,tail_number,equipment_type,created_time,updated_time,scheduled_departure_time,scheduled_arrival_time,actual_departure_time,actual_arrival_time,event_type,origin_icao,destination_icao,flight_key,pax_count,wifi_sessions
0,62bd0a0b-de54-4fce-af4b-a4ee5f9a5eda,4722,LGA,CLE,2026-06-14,N132HQ,NaN,2026-06-15 02:01:12.837,2026-06-15 04:27:04.290704,2026-06-15 00:29:00,2026-06-15 02:22:00,2026-06-15 01:58:00,NaN,OFF,KLGA,KCLE,YX_RPA_LGA_0_4722_2026-06-14,74.0,True
1,9f5bd709-7d8f-44ea-a0dd-b06d267bb6c5,6055,CHO,CLT,2026-07-22,NaN,EMP,2026-07-23 00:13:15.366,2026-07-23 00:13:15.366,2026-07-23 00:00:00,2026-07-23 01:28:00,2026-07-23 00:00:00,NaN,OFF,KCHO,KCLT,PT_PDT_CHO_0_6055_2026-07-22,29.0,False
2,612cc8e4-343d-4b4a-862d-f2530d38c86a,2611,SLC,CLT,2026-06-14,N567UW,NaN,2026-06-14 06:11:23.315,2026-06-15 08:18:07.953339,2026-06-15 05:29:00,2026-06-15 09:25:00,2026-06-15 05:24:00,NaN,OFF,KSLC,KCLT,AA_AAL_SLC_0_2611_2026-06-14,184.0,True
3,e03dcd1f-253b-46f7-a65d-918296c7aeac,1599,SAT,SAT,2026-06-14,N873NN,NaN,2026-06-15 06:46:15.268,2026-06-15 06:46:15.268,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0a501b0b-a991-4776-933f-95103122a79d,1500,DFW,BNA,2026-08-07,N155NN,NaN,2026-08-07 02:31:04.896,2026-08-08 05:39:58.803,2026-08-08 02:35:00,2026-08-08 04:27:00,2026-08-08 03:41:00,2026-08-08 05:40:00,DOOROPEN,KDFW,KBNA,AA_AAL_DFW_0_1500_2026-08-07,188.0,True

In [6]:
data["UNIQUE_FLIGHT_ID"] = (
    data['flight_number'].astype(str).str.strip()
    + " | "
    + data["departure_date"].astype(str)
    + " | "
    + data["origin"].astype(str).str.strip()
    + "-"
    + data["destination"].astype(str).str.strip()
)

In [7]:
data['UNIQUE_FLIGHT_ID'].value_counts()

UNIQUE_FLIGHT_ID
4722 | 2026-06-14 | LGA-CLE    1
6055 | 2026-07-22 | CHO-CLT    1
2611 | 2026-06-14 | SLC-CLT    1
1599 | 2026-06-14 | SAT-SAT    1
1500 | 2026-08-07 | DFW-BNA    1
                              ..
766 | 2026-08-24 | DFW-IND     1
5823 | 2026-08-25 | PHL-ALB    1
2193 | 2026-08-26 | TUS-DFW    1
3101 | 2026-08-26 | DFW-DTW    1
2363 | 2026-08-26 | DEN-ORD    1
Name: count, Length: 625855, dtype: int64

In [8]:
nps_data = pd.read_csv('nps_wifi_score_all2026.csv')

In [9]:
nps_data.head()

,SURVEY_ID,SURVEY_RESPNS_ID,SURVEY_AA_CUST_UNIQUE_ID,SURVEY_LYLTY_ACCT_ID,SURVEY_LYLTY_LEVEL_CD,SEG_DEP_DT,SEG_DEP_AIRPRT_IATA_CD,SEG_ARVL_AIRPRT_IATA_CD,OPERAT_FLIGHT_NBR,FLEET_CD,SUBFLEET_CD,CABIN_FLOWN_CD,WIFI_SATISFACTION_SCR,WIFI_SPEED_SCR,WIFI_PRICE_SCR,WIFI_RLBLTY_SCR,WIFI_EASE_USE_SCR,WIFI_CNCT_EFFRT_SCR,LIKELIHOOD_RECOMMEND_SCL,NET_PROMO_CATG
0,SV_4SJm25NwBp7FfRs,R_6dfccoDUYaEtdct,1.069030e+09,1DW91R6,R,2026-08-02,GPT,DFW,3539,EMJ,E7M,C,NaN,NaN,NaN,NaN,NaN,NaN,10,Promoter
1,SV_4SJm25NwBp7FfRs,R_3qUoFDYOCoZJbfi,4.297665e+07,W254E64,R,2026-05-22,PHL,ORD,3042,321,32C,C,100.0,NaN,NaN,NaN,NaN,NaN,6,Detractor
2,SV_4SJm25NwBp7FfRs,R_6qmHsZyymQPTjKX,8.002585e+09,NaN,N,2026-05-18,ATH,PHL,759,787,788,Y,NaN,NaN,NaN,NaN,NaN,NaN,8,Passive
3,SV_4SJm25NwBp7FfRs,R_6WVCNzZyFf690Rn,8.000967e+09,NaN,N,2026-02-20,ORD,DFW,680,737,38K,Y,50.5,NaN,NaN,NaN,NaN,NaN,1,Detractor
4,SV_4SJm25NwBp7FfRs,R_1eQOLrQ5rjQLQJP,7.786568e+06,D7R2144,T,2026-05-11,SGU,DFW,4818,CRJ,CR9,C,1.0,NaN,NaN,NaN,NaN,NaN,8,Passive

In [10]:
nps_data["UNIQUE_FLIGHT_ID"] = (
    nps_data['OPERAT_FLIGHT_NBR'].astype(str).str.strip()
    + " | "
    + nps_data["SEG_DEP_DT"].astype(str)
    + " | "
    + nps_data["SEG_DEP_AIRPRT_IATA_CD"].astype(str).str.strip()
    + "-"
    + nps_data["SEG_ARVL_AIRPRT_IATA_CD"].astype(str).str.strip()
)

In [11]:
nps_data["UNIQUE_FLIGHT_ID"]

0          3539 | 2026-08-02 | GPT-DFW
1          3042 | 2026-05-22 | PHL-ORD
2           759 | 2026-05-18 | ATH-PHL
3           680 | 2026-02-20 | ORD-DFW
4          4818 | 2026-05-11 | SGU-DFW
                      ...
2050202    6208 | 2026-04-01 | SMF-PHX
2050203     216 | 2026-06-28 | DFW-ATH
2050204    2198 | 2026-05-13 | AUS-DFW
2050205    3172 | 2026-06-06 | MIA-PHX
2050206    2773 | 2026-07-26 | TPA-DCA
Name: UNIQUE_FLIGHT_ID, Length: 2050207, dtype: str

In [12]:
data_combined = data.merge(nps_data, how = 'inner', on = 'UNIQUE_FLIGHT_ID')

In [13]:
pd.set_option('display.max_columns', None)
data_combined.head()

,id,flight_number,origin,destination,departure_date,tail_number,equipment_type,created_time,updated_time,scheduled_departure_time,scheduled_arrival_time,actual_departure_time,actual_arrival_time,event_type,origin_icao,destination_icao,flight_key,pax_count,wifi_sessions,UNIQUE_FLIGHT_ID,SURVEY_ID,SURVEY_RESPNS_ID,SURVEY_AA_CUST_UNIQUE_ID,SURVEY_LYLTY_ACCT_ID,SURVEY_LYLTY_LEVEL_CD,SEG_DEP_DT,SEG_DEP_AIRPRT_IATA_CD,SEG_ARVL_AIRPRT_IATA_CD,OPERAT_FLIGHT_NBR,FLEET_CD,SUBFLEET_CD,CABIN_FLOWN_CD,WIFI_SATISFACTION_SCR,WIFI_SPEED_SCR,WIFI_PRICE_SCR,WIFI_RLBLTY_SCR,WIFI_EASE_USE_SCR,WIFI_CNCT_EFFRT_SCR,LIKELIHOOD_RECOMMEND_SCL,NET_PROMO_CATG
0,62bd0a0b-de54-4fce-af4b-a4ee5f9a5eda,4722,LGA,CLE,2026-06-14,N132HQ,NaN,2026-06-15 02:01:12.837,2026-06-15 04:27:04.290704,2026-06-15 00:29:00,2026-06-15 02:22:00,2026-06-15 01:58:00,NaN,OFF,KLGA,KCLE,YX_RPA_LGA_0_4722_2026-06-14,74.0,True,4722 | 2026-06-14 | LGA-CLE,SV_4SJm25NwBp7FfRs,R_72MsBMvTEKwTikR,1.697849e+09,NaN,N,2026-06-14,LGA,CLE,4722,EMJ,R75,Y,50.50,NaN,NaN,NaN,NaN,NaN,2,Detractor
1,9f5bd709-7d8f-44ea-a0dd-b06d267bb6c5,6055,CHO,CLT,2026-07-22,NaN,EMP,2026-07-23 00:13:15.366,2026-07-23 00:13:15.366,2026-07-23 00:00:00,2026-07-23 01:28:00,2026-07-23 00:00:00,NaN,OFF,KCHO,KCLT,PT_PDT_CHO_0_6055_2026-07-22,29.0,False,6055 | 2026-07-22 | CHO-CLT,SV_4SJm25NwBp7FfRs,R_3L1FKi4iGH5l3aN,6.865332e+08,NaN,N,2026-07-22,CHO,CLT,6055,ERJ,EMP,Y,25.75,NaN,NaN,NaN,NaN,NaN,0,Detractor
2,612cc8e4-343d-4b4a-862d-f2530d38c86a,2611,SLC,CLT,2026-06-14,N567UW,NaN,2026-06-14 06:11:23.315,2026-06-15 08:18:07.953339,2026-06-15 05:29:00,2026-06-15 09:25:00,2026-06-15 05:24:00,NaN,OFF,KSLC,KCLT,AA_AAL_SLC_0_2611_2026-06-14,184.0,True,2611 | 2026-06-14 | SLC-CLT,SV_4SJm25NwBp7FfRs,R_6rJmFHVTfOLNvNe,3.697479e+08,4A4MT76,R,2026-06-14,SLC,CLT,2611,321,A21,Y,NaN,NaN,NaN,NaN,NaN,NaN,7,Passive
3,612cc8e4-343d-4b4a-862d-f2530d38c86a,2611,SLC,CLT,2026-06-14,N567UW,NaN,2026-06-14 06:11:23.315,2026-06-15 08:18:07.953339,2026-06-15 05:29:00,2026-06-15 09:25:00,2026-06-15 05:24:00,NaN,OFF,KSLC,KCLT,AA_AAL_SLC_0_2611_2026-06-14,184.0,True,2611 | 2026-06-14 | SLC-CLT,SV_4SJm25NwBp7FfRs,R_5mVhCDNv4vpVl8R,8.172975e+09,NaN,N,2026-06-14,SLC,CLT,2611,321,A21,Y,50.50,NaN,NaN,NaN,NaN,NaN,3,Detractor
4,0a501b0b-a991-4776-933f-95103122a79d,1500,DFW,BNA,2026-08-07,N155NN,NaN,2026-08-07 02:31:04.896,2026-08-08 05:39:58.803,2026-08-08 02:35:00,2026-08-08 04:27:00,2026-08-08 03:41:00,2026-08-08 05:40:00,DOOROPEN,KDFW,KBNA,AA_AAL_DFW_0_1500_2026-08-07,188.0,True,1500 | 2026-08-07 | DFW-BNA,SV_4SJm25NwBp7FfRs,R_7sjgJFBd8ANIGSB,8.720004e+08,3RK50F2,R,2026-08-07,DFW,BNA,1500,321,32C,Y,75.25,NaN,NaN,NaN,NaN,NaN,1,Detractor

In [14]:
# Convert to datetime
data_combined['actual_arrival_time'] = pd.to_datetime(
    data_combined['actual_arrival_time'],
    errors='coerce'
)

data_combined['scheduled_arrival_time'] = pd.to_datetime(
    data_combined['scheduled_arrival_time'],
    errors='coerce'
)

# Calculate delay
# Result will automatically be NaT if either timestamp is missing
data_combined['delay'] = (
    data_combined['actual_arrival_time']
    - data_combined['scheduled_arrival_time']
)

data_combined['delay_mins'] = (
    data_combined['actual_arrival_time']
    - data_combined['scheduled_arrival_time']
).dt.total_seconds() / 60

data_combined['delay_bucket'] = pd.cut(
    data_combined['delay_mins'],
    bins=[-np.inf, 0, 120, 240, 720, np.inf],
    labels=['Early', '0-2 hrs', '2-4 hrs', '4-12 hrs', '>12 hrs']
)

In [15]:
data_combined['delay_bucket']

0             NaN
1             NaN
2             NaN
3             NaN
4         0-2 hrs
           ...
855068      Early
855069      Early
855070      Early
855071      Early
855072      Early
Name: delay_bucket, Length: 855073, dtype: category
Categories (5, str): ['Early' < '0-2 hrs' < '2-4 hrs' < '4-12 hrs' < '>12 hrs']

In [16]:
data_combined.columns

Index(['id', 'flight_number', 'origin', 'destination', 'departure_date',
       'tail_number', 'equipment_type', 'created_time', 'updated_time',
       'scheduled_departure_time', 'scheduled_arrival_time',
       'actual_departure_time', 'actual_arrival_time', 'event_type',
       'origin_icao', 'destination_icao', 'flight_key', 'pax_count',
       'wifi_sessions', 'UNIQUE_FLIGHT_ID', 'SURVEY_ID', 'SURVEY_RESPNS_ID',
       'SURVEY_AA_CUST_UNIQUE_ID', 'SURVEY_LYLTY_ACCT_ID',
       'SURVEY_LYLTY_LEVEL_CD', 'SEG_DEP_DT', 'SEG_DEP_AIRPRT_IATA_CD',
       'SEG_ARVL_AIRPRT_IATA_CD', 'OPERAT_FLIGHT_NBR', 'FLEET_CD',
       'SUBFLEET_CD', 'CABIN_FLOWN_CD', 'WIFI_SATISFACTION_SCR',
       'WIFI_SPEED_SCR', 'WIFI_PRICE_SCR', 'WIFI_RLBLTY_SCR',
       'WIFI_EASE_USE_SCR', 'WIFI_CNCT_EFFRT_SCR', 'LIKELIHOOD_RECOMMEND_SCL',
       'NET_PROMO_CATG', 'delay', 'delay_mins', 'delay_bucket'],
      dtype='str')

In [17]:
data_combined1 = data_combined[['UNIQUE_FLIGHT_ID', 'flight_number',  'origin', 'destination', 'departure_date',
       'tail_number', 'equipment_type', 'pax_count', 'wifi_sessions', 'delay_mins', 'delay_bucket','SURVEY_ID', 'SURVEY_RESPNS_ID',
       'SURVEY_AA_CUST_UNIQUE_ID', 'SURVEY_LYLTY_ACCT_ID','FLEET_CD',
       'SUBFLEET_CD', 'CABIN_FLOWN_CD', 'WIFI_SATISFACTION_SCR',
       'WIFI_SPEED_SCR', 'WIFI_PRICE_SCR', 'WIFI_RLBLTY_SCR',
       'WIFI_EASE_USE_SCR', 'WIFI_CNCT_EFFRT_SCR', 'LIKELIHOOD_RECOMMEND_SCL',
       'NET_PROMO_CATG']]

In [30]:
data_combined1.head()

,UNIQUE_FLIGHT_ID,flight_number,origin,destination,departure_date,tail_number,equipment_type,pax_count,wifi_sessions,delay_mins,delay_bucket,SURVEY_ID,SURVEY_RESPNS_ID,SURVEY_AA_CUST_UNIQUE_ID,SURVEY_LYLTY_ACCT_ID,FLEET_CD,SUBFLEET_CD,CABIN_FLOWN_CD,WIFI_SATISFACTION_SCR,WIFI_SPEED_SCR,WIFI_PRICE_SCR,WIFI_RLBLTY_SCR,WIFI_EASE_USE_SCR,WIFI_CNCT_EFFRT_SCR,LIKELIHOOD_RECOMMEND_SCL,NET_PROMO_CATG
0,4722 | 2026-06-14 | LGA-CLE,4722,LGA,CLE,2026-06-14,N132HQ,NaN,74.0,True,NaN,NaN,SV_4SJm25NwBp7FfRs,R_72MsBMvTEKwTikR,1.697849e+09,NaN,EMJ,R75,Y,50.50,NaN,NaN,NaN,NaN,NaN,2,Detractor
1,6055 | 2026-07-22 | CHO-CLT,6055,CHO,CLT,2026-07-22,NaN,EMP,29.0,False,NaN,NaN,SV_4SJm25NwBp7FfRs,R_3L1FKi4iGH5l3aN,6.865332e+08,NaN,ERJ,EMP,Y,25.75,NaN,NaN,NaN,NaN,NaN,0,Detractor
2,2611 | 2026-06-14 | SLC-CLT,2611,SLC,CLT,2026-06-14,N567UW,NaN,184.0,True,NaN,NaN,SV_4SJm25NwBp7FfRs,R_6rJmFHVTfOLNvNe,3.697479e+08,4A4MT76,321,A21,Y,NaN,NaN,NaN,NaN,NaN,NaN,7,Passive
3,2611 | 2026-06-14 | SLC-CLT,2611,SLC,CLT,2026-06-14,N567UW,NaN,184.0,True,NaN,NaN,SV_4SJm25NwBp7FfRs,R_5mVhCDNv4vpVl8R,8.172975e+09,NaN,321,A21,Y,50.50,NaN,NaN,NaN,NaN,NaN,3,Detractor
4,1500 | 2026-08-07 | DFW-BNA,1500,DFW,BNA,2026-08-07,N155NN,NaN,188.0,True,73.0,0-2 hrs,SV_4SJm25NwBp7FfRs,R_7sjgJFBd8ANIGSB,8.720004e+08,3RK50F2,321,32C,Y,75.25,NaN,NaN,NaN,NaN,NaN,1,Detractor

In [19]:
data_combined1.groupby('wifi_sessions')['WIFI_SATISFACTION_SCR'].mean()

wifi_sessions
False    41.132554
True     67.641283
Name: WIFI_SATISFACTION_SCR, dtype: float64

In [20]:
data_combined1.groupby('wifi_sessions')['LIKELIHOOD_RECOMMEND_SCL'].mean()

wifi_sessions
False    6.655189
True     6.741173
Name: LIKELIHOOD_RECOMMEND_SCL, dtype: float64

In [21]:
data_combined1.groupby(['wifi_sessions', 'delay_bucket'])['LIKELIHOOD_RECOMMEND_SCL'].mean()

wifi_sessions  delay_bucket
False          Early           7.266889
               0-2 hrs         6.422253
               2-4 hrs         4.308002
               4-12 hrs        2.672340
               >12 hrs         2.187902
True           Early           7.658593
               0-2 hrs         6.189391
               2-4 hrs         3.442045
               4-12 hrs        2.205342
               >12 hrs         1.744634
Name: LIKELIHOOD_RECOMMEND_SCL, dtype: float64

In [22]:
flight_variation = (
    data_combined1.groupby('UNIQUE_FLIGHT_ID')['LIKELIHOOD_RECOMMEND_SCL']
    .agg(
        Count='count',
        Min='min',
        Max='max'
    )
    .reset_index()
)

flight_variation.sort_values(by = 'Count', inplace = True, ascending = False)
flight_variation.head()

                   UNIQUE_FLIGHT_ID  Count  Min  Max
346611   743 | 2026-07-04 | BCN-PHL     27    0   10
94508    217 | 2026-06-08 | ATH-DFW     25    0   10
229728   407 | 2026-05-26 | ANC-DFW     25    0   10
94499    217 | 2026-05-30 | ATH-DFW     25    0    9
79582   2002 | 2026-07-25 | LAS-JFK     24    0    5

In [29]:
from IPython.display import display, HTML

display(
    HTML(
        f"""
        <div style="height:500px; overflow-y:auto;">
            {data_combined[data_combined['UNIQUE_FLIGHT_ID'] == '743 | 2026-07-04 | BCN-PHL'].to_html()}
        </div>
        """
    )
)